// Auto-generated by scripts/build-sticker-assets.mjs — do not edit manually
//
// 贴纸一贴一个模块。之前 20 个贴纸的 SVG 字符串合计 768KB，全被打进 ShareSheet
// chunk —— 每个点「分享」的人都要先下完它们，哪怕只用得到卡片上那一个。
// 现在：
//   选择器  → thumb/*.png（几十字节的蒙版，配合 background-color 上色，跟随主题）
//   卡片    → 只 load() 当前选中的那一个；除默认贴纸外都是独立 chunk
// kitty 静态引入（默认贴纸，卡片首帧就要用）。

import kittyThumb from './thumb/kitty.png';
import glanceThumb from './thumb/glance.png';
import puffyThumb from './thumb/puffy.png';
import rockstarThumb from './thumb/rockstar.png';
import chillThumb from './thumb/chill.png';
import vibingThumb from './thumb/vibing.png';
import scholarThumb from './thumb/scholar.png';
import belleThumb from './thumb/belle.png';
import fluffyThumb from './thumb/fluffy.png';
import duoThumb from './thumb/duo.png';
import sageThumb from './thumb/sage.png';
import loyalThumb from './thumb/loyal.png';
import jesterThumb from './thumb/jester.png';
import classicThumb from './thumb/classic.png';
import bookwormThumb from './thumb/bookworm.png';
import stardustThumb from './thumb/stardust.png';
import waitingThumb from './thumb/waiting.png';
import hammockThumb from './thumb/hammock.png';
import keyboardThumb from './thumb/keyboard.png';
import stampingThumb from './thumb/stamping.png';
import kittySvg from './01-kitty.svg?raw';

export interface StickerOption {
  id: string;
  name: string;
}

export interface Sticker extends StickerOption {
  /** 选择器里的缩略图。是 PNG 蒙版：上色靠容器的 background-color，不是 fill。 */
  thumb: string;
  /** 取这张贴纸的 SVG 几何。除默认贴纸外都是单独一个 chunk。 */
  load: () => Promise<string>;
}

export const STICKERS: Sticker[] = [
  { id: 'kitty', name: 'Kitty', thumb: kittyThumb, load: () => Promise.resolve(kittySvg) },
  { id: 'glance', name: 'Glance', thumb: glanceThumb, load: () => import('./02-glance.svg?raw').then((m) => m.default) },
  { id: 'puffy', name: 'Puffy', thumb: puffyThumb, load: () => import('./03-puffy.svg?raw').then((m) => m.default) },
  { id: 'rockstar', name: 'Rockstar', thumb: rockstarThumb, load: () => import('./04-rockstar.svg?raw').then((m) => m.default) },
  { id: 'chill', name: 'Chill', thumb: chillThumb, load: () => import('./05-chill.svg?raw').then((m) => m.default) },
  { id: 'vibing', name: 'Vibing', thumb: vibingThumb, load: () => import('./06-vibing.svg?raw').then((m) => m.default) },
  { id: 'scholar', name: 'Scholar', thumb: scholarThumb, load: () => import('./07-scholar.svg?raw').then((m) => m.default) },
  { id: 'belle', name: 'Belle', thumb: belleThumb, load: () => import('./08-belle.svg?raw').then((m) => m.default) },
  { id: 'fluffy', name: 'Fluffy', thumb: fluffyThumb, load: () => import('./09-fluffy.svg?raw').then((m) => m.default) },
  { id: 'duo', name: 'Duo', thumb: duoThumb, load: () => import('./10-duo.svg?raw').then((m) => m.default) },
  { id: 'sage', name: 'Sage', thumb: sageThumb, load: () => import('./11-sage.svg?raw').then((m) => m.default) },
  { id: 'loyal', name: 'Loyal', thumb: loyalThumb, load: () => import('./12-loyal.svg?raw').then((m) => m.default) },
  { id: 'jester', name: 'Jester', thumb: jesterThumb, load: () => import('./13-jester.svg?raw').then((m) => m.default) },
  { id: 'classic', name: 'Classic', thumb: classicThumb, load: () => import('./14-classic.svg?raw').then((m) => m.default) },
  { id: 'bookworm', name: 'Bookworm', thumb: bookwormThumb, load: () => import('./15-bookworm.svg?raw').then((m) => m.default) },
  { id: 'stardust', name: 'Stardust', thumb: stardustThumb, load: () => import('./16-stardust.svg?raw').then((m) => m.default) },
  { id: 'waiting', name: 'Waiting', thumb: waitingThumb, load: () => import('./17-waiting.svg?raw').then((m) => m.default) },
  { id: 'hammock', name: 'Hammock', thumb: hammockThumb, load: () => import('./18-hammock.svg?raw').then((m) => m.default) },
  { id: 'keyboard', name: 'Keyboard', thumb: keyboardThumb, load: () => import('./19-keyboard.svg?raw').then((m) => m.default) },
  { id: 'stamping', name: 'Stamping', thumb: stampingThumb, load: () => import('./20-stamping.svg?raw').then((m) => m.default) },
];

/** 已经静态打进来的贴纸（默认那几张）。拿不到就是 null，调用方去 await load()。 */
export function eagerStickerSvg(id: string): string | null {
  return EAGER[id] ?? null;
}

const EAGER: Record<string, string> = { kitty: kittySvg };

export function findSticker(id: string): Sticker | undefined {
  return STICKERS.find((s) => s.id === id);
}

/** 按 id 取 SVG。id 不认识就抛错 —— 这是代码写错了，不是运行时的正常分支。 */
export function loadStickerSvg(id: string): Promise<string> {
  const sticker = findSticker(id);
  if (!sticker) return Promise.reject(new Error(`未知贴纸：${id}`));
  return sticker.load();
}
